# creation rules are evaluated sequentially, the first match wins
creation_rules:
    # upon creation of a file that matches the pattern *.poc.yaml,
    # POC KMS master key is used
  - filename_regex: \.poc\.ya?ml$
    kms: arn:aws:kms:ap-southeast-2:224093794013:key/3406f274-9cf1-43b1-a8d1-0b35c896c220
    # kms: arn:aws:kms:ap-southeast-2:224093794013:key/3406f274-9cf1-43b1-a8d1-0b35c896c220

  # DEV KMS master key is used
  - filename_regex: \.dev\.ya?ml$
    kms: arn:aws:kms:ap-southeast-2:439149920780:key/f8b40a9d-07ca-495b-a6c7-255a146e1555

  # QAT KMS master key is used
  - filename_regex: \.qat\.ya?ml$
    kms: arn:aws:kms:ap-southeast-2:829292609546:key/8a9e64d0-1056-4e5e-b0cd-ee32c518b1d0

  # PRD KMS master key is used
  - filename_regex: \.prd\.ya?ml$
    kms: arn:aws:kms:ap-southeast-2:750438120855:key/790dd78f-360b-417e-8527-97827be29f98

  # The absence of a filename_regex means it will match everything
  # DEFAULT KMS master key is used
  - kms: arn:aws:kms:ap-southeast-2:224093794013:key/bed2d990-a5bf-4875-9930-aa20dcb71390
